
steps:

- id: 'test'
  # name: 'python'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
    # - "vault_token=${_VAULT_TOKEN}"
     - 'INFRACTL_HOME=/infractl'
  args:
  - '-c'
  - |
    mv /infractl/terraform /infractl/terraform-orig
    ln -s /workspace/terraform /infractl/terraform
    cd /infractl
    infractl terraform plan --module core --env itops-playground --upgrade-on-init --force
#substitutions:
 # _VAULT_TOKEN: ""
logsBucket: gs://logs_cloud_build
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
