
steps:

- id: 'test'
  name: 'python'
  entrypoint: bash
  args:
  - '-c'
  - |
    cd scripts
    pip install --upgrade pip
    pip install -r requirements.txt
    python main.py

options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
