
steps:

- id: 'buid tf'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
     - "vault_token=${_VAULT_TOKEN}"
  args:
  - '-c'
  - |
    export INFRACTL_VAULT_TOKEN=$vault_token
    infractl terraform plan --module terraform/environment/dev --env itops-playground
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
