
steps:

- id: 'test'
  # name: 'python'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
     - "vault_token=${_VAULT_TOKEN}"
     - 'INFRACTL_HOME=/infractl'
  args:
  - '-c'
  - |
    export VAULT_TOKEN=$vault_token
    mv /infractl/terraform /infractl/terraform-orig
    mv /workspace/terraform /infractl/terraform
    infractl terraform plan --module core --env itops-playground --upgrade-on-init --force
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
