
steps:

- id: 'test'
  # name: 'python'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
     #- "vault_ad=${_VAULT_TOKEN}"
     - 'INFRACTL_HOME=/infractl' 
     - 'VAULT_ADDR=https://itops-playground-vault-01.corp.oreilly.com:8200'
  args:
  - '-c'
  - | 
    apt -y update && apt -y install curl
    jwt=`curl -H "Metadata-Flavor: Google" 'http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=https%3A%2F%2Fitops-playground-vault-01.corp.oreilly.com%3A8200'`
    echo $$jwt
    echo "10.200.80.2   itops-playground-vault-01.corp.oreilly.com" >> /etc/hosts
    vault login -method=gcp role="cloudbuild-role"
    token=`vault read gcp/static-account/tf-token/token`
    echo $token
    mv /infractl/terraform /infractl/terraform-orig
    ln -s /workspace/terraform /infractl/terraform
    cd /infractl
    infractl --vault-token "$token" terraform plan --module core --env itops-playground --upgrade-on-init --force
logsBucket: gs://logs_cloud_build
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
