
# steps:

# - id: 'buid tf'
#   name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
#   entrypoint: bash
#   env:
#      - "vault_token=${_VAULT_TOKEN}"
#   args:
#   - '-c'
#   - |
#     export INFRACTL_VAULT_TOKEN=$vault_token
#     infractl terraform plan --module terraform/environment/dev --env itops-playground
# options:
#   pool:
#     name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
steps:

- id: 'test'
  # name: 'python'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
     - 'INFRACTL_HOME=/infractl'
     - "vault_token=${_VAULT_TOKEN}"
  args:
  - '-c'
  - |
    echo $vault_token
    mv /infractl/terraform /infractl/terraform-orig
    ln -s /workspace/terraform /infractl/terraform
    cd /infractl
    ls terraform
    infractl --vault-token=$vault_token terraform plan --module environments/dev --env itops-playground --force
#substitutions:
 # _VAULT_TOKEN: ""
logsBucket: gs://logs_cloud_build
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'