
steps:

- id: 'test'
  name: 'python'
  entrypoint: bash
  env:
     - "vault_token=${_VAULT_TOKEN}"
  args:
  - '-c'
  - |
    cd scripts
    pip install --upgrade pip
    pip install -r requirements.txt
    python main.py
    echo $vault_token

options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
