
steps:

- id: 'test'
  # name: 'python'
  name: gcr.io/common-build/infractl:latest
  entrypoint: bash
  env:
     - "vault_token=${_VAULT_TOKEN}"
  args:
  - '-c'
  - |
    export VAULT_TOKEN=$vault_token
    docker compose run --rm infractl terraform plan --module terraform/environments/dev --env itops-playground
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
