
steps:
- id: 'gcloud auth'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - | 
    gcloud auth print-identity-token >/workspace/token

- id: 'plan'
  # name: 'python'
  name: us-central1-docker.pkg.dev/itops-playground/container/infractl:latest
  entrypoint: bash
  env:
     #- "vault_ad=${_VAULT_TOKEN}"
     - 'INFRACTL_HOME=/infractl' 
     - 'VAULT_ADDR=https://itops-playground-vault-01.corp.oreilly.com:8200'
  args:
  - '-c'
  - | 
    token=`cat /workspace/token`
    echo $token
    echo "10.200.80.2   itops-playground-vault-01.corp.oreilly.com" >> /etc/hosts
    vault login -method=gcp role="cloudbuild-role"
    token=`vault read gcp/static-account/tf-token/token`
    echo $token
    mv /infractl/terraform /infractl/terraform-orig
    ln -s /workspace/terraform /infractl/terraform
    cd /infractl
    infractl --vault-token "$token" terraform plan --module core --env itops-playground --upgrade-on-init --force
logsBucket: gs://logs_cloud_build
options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
