
steps:

- id: 'test'
  name: 'python'
  args:
  - '-c'
  - |
    cd scripts
    pip install -r requitements.txt
    python main.py

options:
  pool:
    name: 'projects/itops-playground/locations/us-central1/workerPools/itops-playground-cb'
  
